-- Supabase schema for wedding invitation data

create table if not exists public.rsvp_guests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  guest_slug text,
  attendance text not null check (attendance in ('attending', 'not_attending', 'pending')),
  number_of_guests integer not null default 1,
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.guest_list (
  id bigint generated by default as identity primary key,
  name text not null,
  title text,
  whatsapp text not null,
  slug text not null unique,
  invited boolean not null default false,
  is_group boolean not null default false,
  rsvp_status text not null check (rsvp_status in ('attending', 'not_attending', 'not_responded')) default 'not_responded',
  message_sent boolean not null default false,
  message_sent_at timestamptz,
  rsvp_message text,
  country text not null check (country in ('Indonesia', 'Singapore', 'United States', 'Netherlands')) default 'Indonesia',
  language text not null check (language in ('id', 'en')) default 'id',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.live_stream_settings (
  id bigint primary key,
  url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists guest_list_slug_idx on public.guest_list (slug);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists guest_list_set_updated_at on public.guest_list;
create trigger guest_list_set_updated_at
before update on public.guest_list
for each row
execute function public.set_updated_at();

drop trigger if exists live_stream_settings_set_updated_at on public.live_stream_settings;
create trigger live_stream_settings_set_updated_at
before update on public.live_stream_settings
for each row
execute function public.set_updated_at();

-- RLS policies for anon key access (adjust as needed)
alter table public.guest_list enable row level security;
alter table public.rsvp_guests enable row level security;
alter table public.live_stream_settings enable row level security;

drop policy if exists "guest_list_select" on public.guest_list;
create policy "guest_list_select"
on public.guest_list
for select
using (true);

drop policy if exists "guest_list_insert" on public.guest_list;
create policy "guest_list_insert"
on public.guest_list
for insert
with check (true);

drop policy if exists "guest_list_update" on public.guest_list;
create policy "guest_list_update"
on public.guest_list
for update
using (true)
with check (true);

drop policy if exists "guest_list_delete" on public.guest_list;
create policy "guest_list_delete"
on public.guest_list
for delete
using (true);

drop policy if exists "rsvp_select" on public.rsvp_guests;
create policy "rsvp_select"
on public.rsvp_guests
for select
using (true);

drop policy if exists "rsvp_insert" on public.rsvp_guests;
create policy "rsvp_insert"
on public.rsvp_guests
for insert
with check (true);

drop policy if exists "rsvp_delete" on public.rsvp_guests;
create policy "rsvp_delete"
on public.rsvp_guests
for delete
using (true);

drop policy if exists "live_stream_settings_select" on public.live_stream_settings;
create policy "live_stream_settings_select"
on public.live_stream_settings
for select
using (true);

drop policy if exists "live_stream_settings_upsert" on public.live_stream_settings;
create policy "live_stream_settings_upsert"
on public.live_stream_settings
for insert
with check (true);

drop policy if exists "live_stream_settings_update" on public.live_stream_settings;
create policy "live_stream_settings_update"
on public.live_stream_settings
for update
using (true)
with check (true);
